# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/boltz/00_dock.ipynb.

# %% auto #0
__all__ = ['prepare_boltz', 'run_boltz', 'plot_scatter_spearman']

# %% ../../nbs/boltz/00_dock.ipynb #3b60daa9
# basics
import subprocess
from pathlib import Path

# %% ../../nbs/boltz/00_dock.ipynb #71a6ad95
def prepare_boltz(seq: str, # Amino acid sequence of the protein the protein
                    smiles: str, # SMILES string of the ligand
                    fname: str, # Output filename (should end with .yaml)
                    ):
    "Create a YAML file for protein-ligand affinity prediction."
    yaml_content = f"""version: 1
sequences:
  - protein:
      id: "A"
      sequence: "{seq}"
  - ligand:
      id: "B"
      smiles: "{smiles}"
properties:
  - affinity:
      binder: "B"
"""
    with open(fname, "w") as f:
        f.write(yaml_content)

# %% ../../nbs/boltz/00_dock.ipynb #486e2576
def run_boltz(file_list:list[Path], # list of .yaml path in Pathlib object
                     api_key,# API key for Boltz-Lab
                     job_name=None, # job name appeared in boltz
                     ):
    
    "Run Boltz-Lab predictions for a list of YAML files."

    # config key
    subprocess.run(
        ["boltz-lab", "config", "--api-key", api_key.strip()],
        check=True
    )
    failed = []

    for file in file_list:
        print(f"\nSubmitting: {str(file)}")

        result = subprocess.run(
            ["boltz-lab", "predict", str(file),
             "--no-wait", # for batch run, so no need to wait the results til the next
             "--name",file.stem if job_name is None else job_name, # job name appeared in boltz
             ],
            capture_output=True,
            text=True,
        )

        if result.returncode != 0: failed.append(file.name)

        print(result.stdout)


    print("\n======== SUMMARY ========")
    print(f"Total: {len(file_list)}")
    print(f"Failed: {len(failed)}")

    return failed


# %% ../../nbs/boltz/00_dock.ipynb #45b0e6aa
import matplotlib.pyplot as plt
import seaborn as sns, numpy as np
from scipy.stats import spearmanr

# %% ../../nbs/boltz/00_dock.ipynb #eec74db7
def plot_scatter_spearman(data, x, y, ax=None):
    """
    Plot scatter + Spearman correlation and p-value annotation.
    """
    if ax is None:
        ax = plt.gca()

    # Drop NA
    sub = data[[x, y]].dropna()
    x_vals = sub[x]
    y_vals = sub[y]

    # Compute Spearman
    rho, p = spearmanr(x_vals, y_vals)

    # Plot
    sns.scatterplot(data=sub, x=x, y=y, ax=ax)

    # Annotate
    text = f"Spearman ρ = {rho:.3f}\np = {p:.2e}"
    ax.text(
        0.98, 0.98,   # x, y in axes fraction
        text,
        transform=ax.transAxes,
        ha='right',          # horizontal align
        va='top',            # vertical align
        fontsize=11,
        bbox=dict(boxstyle="round", facecolor="white", alpha=0.7)
    )

    ax.set_title(f'{x} vs {y}')

    return rho, p
