# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kdock',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/kdock',
                'lib_path': 'kdock'},
  'syms': {'kdock.core': {'kdock.core.foo': ('core.html#foo', 'kdock/core.py')}}}
