# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_gnina_AF3_rescore.ipynb.

# %% auto 0
__all__ = ['ChainSelect', 'rename_residues', 'split_cif', 'pdb2sdf', 'prepare_rec_lig', 'gnina_rescore', 'extract_gnina_output',
           'get_gnina_rescore']

# %% ../nbs/05_gnina_AF3_rescore.ipynb 3
import pandas as pd
import re, os, subprocess, py3Dmol
from Bio.PDB import MMCIFParser, PDBIO, Select
from rdkit import Chem
from rdkit.Chem import AllChem

# %% ../nbs/05_gnina_AF3_rescore.ipynb 5
class ChainSelect(Select):
    "Select chain to save"
    def __init__(self, chain_ids):
        self.chain_ids = chain_ids
    def accept_chain(self, chain):
        return chain.get_id() in self.chain_ids

# %% ../nbs/05_gnina_AF3_rescore.ipynb 6
def rename_residues(structure, chain_id, new_resname='LIG'):
    "Rename residue name from LIG_L to LIG as LIG_L exceeds lengths and leads to error in RDKit"
    for model in structure:
        for chain in model:
            if chain.id == chain_id:
                for residue in chain:
                    residue.resname = new_resname

# %% ../nbs/05_gnina_AF3_rescore.ipynb 7
def split_cif(cif_path, chainA_pdb_path, chainL_pdb_path):
    "Split AF3 output CIF to protein and ligand PDBs"
    parser = MMCIFParser(QUIET=True)
    structure = parser.get_structure('complex', cif_path)
    rename_residues(structure, chain_id='L', new_resname='LIG')
    io = PDBIO()
    io.set_structure(structure)
    io.save(chainA_pdb_path, ChainSelect('A'))  # receptor
    io.save(chainL_pdb_path, ChainSelect('L'))  # ligand

# %% ../nbs/05_gnina_AF3_rescore.ipynb 8
def pdb2sdf(pdb_path, sdf_path):
    "Convert ligand pdb to sdf file"
    mol = Chem.MolFromPDBFile(pdb_path, sanitize=True, removeHs=False)
    if mol:
        writer = Chem.SDWriter(sdf_path)
        writer.write(mol)
        writer.close()
        return None
    else:
        print('Conversion failed for:', pdb_path)
        return pdb_path

# %% ../nbs/05_gnina_AF3_rescore.ipynb 9
def prepare_rec_lig(cif_path, chainA_pdb_path, chainL_sdf_path):
    "Split AF3 cif to protein.pdb (chainA) and ligand.sdf (chainL) "
    tmp = 'tmp_lig.pdb'
    split_cif(cif_path, chainA_pdb_path, tmp)
    failed = pdb2sdf(tmp, chainL_sdf_path)
    try:
        os.remove(tmp)
    except OSError:
        pass
    return failed

# %% ../nbs/05_gnina_AF3_rescore.ipynb 14
def gnina_rescore(protein_pdb, # receptor file
                  ligand_sdf, # ligand file
                  ):
    
    command = ['./gnina', 
               '-r', protein_pdb, 
               '-l', ligand_sdf, 
               '--minimize']

    result = subprocess.run(command, capture_output=True, text=True)
    return result.stdout

# %% ../nbs/05_gnina_AF3_rescore.ipynb 17
def extract_gnina_output(txt):
    "Extract GNINA output text to dictionary."
    
    pattern = re.search(
        r"Affinity:\s+(?P<binding_energy>[-.\d]+)\s+(?P<uncertainty>[-.\d]+).*?"
        r"RMSD:\s+(?P<RMSD>[-.\d]+).*?"
        r"CNNscore:\s+(?P<CNNscore>[-.\d]+).*?"
        r"CNNaffinity:\s+(?P<CNNaffinity>[-.\d]+).*?"
        r"CNNvariance:\s+(?P<CNNvariance>[-.\d]+)",
        txt,
        re.DOTALL)

    if not pattern:
        print("Failed to match GNINA output format.")
    
    return {k: float(v) for k, v in pattern.groupdict().items()} # convert values to float

# %% ../nbs/05_gnina_AF3_rescore.ipynb 20
def get_gnina_rescore(protein_pdb,ligand_sdf):
    out = gnina_rescore('chain_A.pdb','chain_L.sdf')
    return extract_gnina_output(out)
